#pragma once

#include "driver/gpio.h"
#include "driver/ledc.h"
#include "sdkconfig.h"

#define ROBOT_AGENT_IP CONFIG_ROBOT_AGENT_IP
#define ROBOT_AGENT_PORT CONFIG_ROBOT_AGENT_PORT

#define ROBOT_LEFT_PWM_GPIO GPIO_NUM_25
#define ROBOT_LEFT_IN_A_GPIO GPIO_NUM_27
#define ROBOT_LEFT_IN_B_GPIO GPIO_NUM_26

#define ROBOT_RIGHT_PWM_GPIO GPIO_NUM_13
#define ROBOT_RIGHT_IN_A_GPIO GPIO_NUM_12
#define ROBOT_RIGHT_IN_B_GPIO GPIO_NUM_14

#define ROBOT_LEFT_ENCODER_GPIO GPIO_NUM_33
#define ROBOT_RIGHT_ENCODER_GPIO GPIO_NUM_32

#define ROBOT_LEFT_PWM_CHANNEL LEDC_CHANNEL_1
#define ROBOT_RIGHT_PWM_CHANNEL LEDC_CHANNEL_0
#define ROBOT_PWM_TIMER LEDC_TIMER_0
#define ROBOT_PWM_MODE LEDC_LOW_SPEED_MODE
#define ROBOT_PWM_RESOLUTION LEDC_TIMER_10_BIT
#define ROBOT_PWM_FREQUENCY_HZ 200
#define ROBOT_PWM_MAX_DUTY 1023

#define ROBOT_WHEEL_DIAMETER_M 0.065
#define ROBOT_TRACK_WIDTH_M 0.135
#define ROBOT_ENCODER_TICKS_PER_REV 300.0
#define ROBOT_PI 3.14159265358979323846

#define ROBOT_METERS_PER_TICK \
    ((ROBOT_PI * ROBOT_WHEEL_DIAMETER_M) / ROBOT_ENCODER_TICKS_PER_REV)

#define ROBOT_TICKS_PER_METER (1.0 / ROBOT_METERS_PER_TICK)

#define ROBOT_CONTROL_PERIOD_MS 50
#define ROBOT_COMMAND_TIMEOUT_US 200000

#define ROBOT_KP 0.10
#define ROBOT_KI 0.02
#define ROBOT_FILTER_ALPHA 0.90
#define ROBOT_LEFT_FEEDFORWARD 0.085
#define ROBOT_RIGHT_FEEDFORWARD 0.075
#define ROBOT_SYNC_GAIN 0.05
#define ROBOT_INTEGRAL_LIMIT 8.0

#define ROBOT_MOTOR_DEADZONE_PERCENT 7.0
#define ROBOT_MOTOR_MAX_PERCENT 90.0

#define ROBOT_CONTROL_TASK_STACK 4096
#define ROBOT_CONTROL_TASK_PRIORITY 10
#define ROBOT_CONTROL_TASK_CORE 1

#define ROBOT_MICROROS_TASK_STACK 10240
#define ROBOT_MICROROS_TASK_PRIORITY 5
#define ROBOT_MICROROS_TASK_CORE 0
